# Generated by Django 6.0.8 on 2026-08-16 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='球队名称')),
                ('short_name', models.CharField(blank=True, max_length=30, verbose_name='球队简称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '球队',
                'verbose_name_plural': '球队',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='场地名称')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='场地位置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '比赛场地',
                'verbose_name_plural': '比赛场地',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='赛事名称')),
                ('season', models.CharField(help_text='例如：2026赛季或2026春季', max_length=30, verbose_name='赛季')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否进行中')),
            ],
            options={
                'verbose_name': '赛事',
                'verbose_name_plural': '赛事',
                'ordering': ['-season', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'season'), name='unique_competition_season')],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('match_number', models.CharField(blank=True, max_length=30, verbose_name='场次编号')),
                ('round_name', models.CharField(blank=True, help_text='例如：小组赛第1轮、半决赛', max_length=50, verbose_name='轮次')),
                ('kickoff_at', models.DateTimeField(db_index=True, verbose_name='开球时间')),
                ('match_level', models.CharField(blank=True, max_length=50, verbose_name='赛事级别')),
                ('status', models.CharField(choices=[('scheduled', '正常进行'), ('cancelled', '已取消'), ('finished', '已结束')], default='scheduled', max_length=20, verbose_name='比赛状态')),
                ('assignment_status', models.CharField(choices=[('draft', '排班草稿'), ('published', '已经发布')], db_index=True, default='draft', max_length=20, verbose_name='裁判安排发布状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='安排发布时间')),
                ('notes', models.TextField(blank=True, verbose_name='比赛备注')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='scheduling.competition', verbose_name='所属赛事')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_matches', to=settings.AUTH_USER_MODEL, verbose_name='录入人员')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='scheduling.team', verbose_name='客队')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='scheduling.team', verbose_name='主队')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='scheduling.venue', verbose_name='比赛场地')),
            ],
            options={
                'verbose_name': '比赛',
                'verbose_name_plural': '比赛',
                'ordering': ['kickoff_at', 'id'],
                'permissions': [('publish_assignments', '可以发布裁判安排')],
            },
        ),
        migrations.CreateModel(
            name='RefereeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='联系电话')),
                ('level', models.CharField(choices=[('national', '国家级'), ('level_1', '一级'), ('level_2', '二级'), ('level_3', '三级'), ('trainee', '见习'), ('other', '其他')], default='other', max_length=20, verbose_name='裁判等级')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可参与排班')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referee_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户账号')),
            ],
            options={
                'verbose_name': '裁判资料',
                'verbose_name_plural': '裁判资料',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('position', models.PositiveSmallIntegerField(choices=[(1, '主裁判'), (2, '第一助理裁判'), (3, '第二助理裁判'), (4, '第四官员')], verbose_name='执法岗位')),
                ('response_status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已经确认'), ('leave', '申请请假')], db_index=True, default='pending', max_length=20, verbose_name='确认状态')),
                ('response_note', models.TextField(blank=True, verbose_name='确认或请假说明')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='回应时间')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='排班人员')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scheduling.match', verbose_name='比赛')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='scheduling.refereeprofile', verbose_name='裁判员')),
            ],
            options={
                'verbose_name': '裁判安排',
                'verbose_name_plural': '裁判安排',
                'ordering': ['match__kickoff_at', 'position'],
                'constraints': [models.UniqueConstraint(fields=('match', 'position'), name='unique_match_position'), models.UniqueConstraint(fields=('match', 'referee'), name='unique_referee_per_match')],
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['assignment_status', 'kickoff_at'], name='match_publish_time_idx'),
        ),
    ]
