# Generated by Django 6.0.8 on 2026-10-09 02:14

import scheduling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(default=scheduling.models.generate_invite_code, help_text='注册时不区分大小写。建议使用自动生成的随机码。', max_length=40, unique=True, verbose_name='邀请码')),
                ('note', models.CharField(blank=True, help_text='例如：2026 秋季裁判群', max_length=100, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('expires_at', models.DateTimeField(blank=True, help_text='留空表示不过期。', null=True, verbose_name='过期时间')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='留空表示不限次数。', null=True, verbose_name='最多使用次数')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='已使用次数')),
            ],
            options={
                'verbose_name': '邀请码',
                'verbose_name_plural': '邀请码',
                'ordering': ['-created_at'],
            },
        ),
    ]
