# Generated by Django 6.0.8 on 2026-10-09 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAssignmentSummary',
            fields=[
            ],
            options={
                'verbose_name': '裁判安排',
                'verbose_name_plural': '裁判安排',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scheduling.match',),
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['match__kickoff_at', 'position'], 'verbose_name': '裁判安排明细', 'verbose_name_plural': '裁判安排明细'},
        ),
    ]
