"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "axes",

    "scheduling",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 必须放在最后，用于拦截被锁定账号的登录请求。
    "axes.middleware.AxesMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "scheduling.context_processors.site",
                "scheduling.context_processors.notifications",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

# 项目自带的翻译（补充第三方应用缺少的简体中文）；以后增加英文切换也放在这里。
LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
# 项目自带的静态资源（校徽、会徽等）
STATICFILES_DIRS = [BASE_DIR / "static"]

ON_VERCEL = os.environ.get("VERCEL") == "1"

# Vercel 在构建时 collectstatic 并由 CDN 提供静态文件，使用 Django 默认存储；
# Docker 部署由 whitenoise 提供带哈希文件名的压缩静态文件。
if not ON_VERCEL:
    STORAGES = {
        "default": {
            "BACKEND": (
                "django.core.files.storage.FileSystemStorage"
            ),
        },
        "staticfiles": {
            "BACKEND": (
                "whitenoise.storage."
                "CompressedManifestStaticFilesStorage"
            ),
        },
    }


# Referee System settings


def env_list(name, default=""):
    return [
        value.strip()
        for value in os.environ.get(name, default).split(",")
        if value.strip()
    ]


SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

DEBUG = os.environ.get("DJANGO_DEBUG", "0") == "1"

ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    "127.0.0.1,localhost",
)

CSRF_TRUSTED_ORIGINS = env_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS"
)

for variable in (
    "VERCEL_URL",
    "VERCEL_PROJECT_PRODUCTION_URL",
    "VERCEL_BRANCH_URL",
):
    if os.environ.get(variable):
        ALLOWED_HOSTS.append(os.environ[variable])

if ON_VERCEL:
    if DEBUG:
        raise ImproperlyConfigured("DJANGO_DEBUG must be 0 on Vercel.")
    if not os.environ.get("DATABASE_URL"):
        raise ImproperlyConfigured("DATABASE_URL is required on Vercel.")

if os.environ.get("DATABASE_URL"):
    # Serverless 环境不保留长连接，连接复用交给 Neon pooler。
    DATABASES = {"default": dj_database_url.parse(
        os.environ["DATABASE_URL"], conn_max_age=0, ssl_require=True,
    )}
    DATABASES["default"]["DISABLE_SERVER_SIDE_CURSORS"] = True
    DATABASES["default"]["OPTIONS"]["connect_timeout"] = 10
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ["POSTGRES_DB"],
            "USER": os.environ["POSTGRES_USER"],
            "PASSWORD": os.environ["POSTGRES_PASSWORD"],
            "HOST": os.environ.get("POSTGRES_HOST", "db"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
            "CONN_MAX_AGE": 60,
            "CONN_HEALTH_CHECKS": True,
        }
    }

TIME_ZONE = "Asia/Shanghai"
USE_TZ = True

# Vercel 始终通过 HTTPS 访问，因此强制开启。
HTTPS_ENABLED = (
    ON_VERCEL
    or os.environ.get("DJANGO_HTTPS_ENABLED", "0") == "1"
)

SECURE_SSL_REDIRECT = HTTPS_ENABLED
SESSION_COOKIE_SECURE = HTTPS_ENABLED
CSRF_COOKIE_SECURE = HTTPS_ENABLED

if HTTPS_ENABLED:
    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https",
    )
    SECURE_HSTS_SECONDS = int(
        os.environ.get(
            "DJANGO_SECURE_HSTS_SECONDS",
            "3600",
        )
    )
    SECURE_HSTS_INCLUDE_SUBDOMAINS = (
        os.environ.get(
            "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
            "0",
        )
        == "1"
    )
    SECURE_HSTS_PRELOAD = (
        os.environ.get(
            "DJANGO_SECURE_HSTS_PRELOAD",
            "0",
        )
        == "1"
    )
else:
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# 网站名称（页面标题、后台标题、邮件和导出文件都使用这里）
SITE_NAME = "华中科技大学足球协会"

# 用户登录与退出
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "scheduling:home"
LOGOUT_REDIRECT_URL = "login"

# 登录失败限制（django-axes）
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# 同一用户名连续失败 5 次后锁定 15 分钟，成功登录后清零。
# 只按用户名锁定，避免校园网共用出口 IP 时误锁所有人。
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(minutes=15)
AXES_LOCKOUT_PARAMETERS = ["username"]
# W006 针对按 User-Agent/Cookie 组合锁定的配置；只按用户名锁定时更换它们无法绕过。
SILENCED_SYSTEM_CHECKS = ["axes.W006"]
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_TEMPLATE = "registration/locked_out.html"
AXES_CLIENT_IP_CALLABLE = "scheduling.auth.client_ip"

# 邮件通知（SMTP）。未设置 EMAIL_HOST 时只发站内通知。
# 例：QQ 邮箱 smtp.qq.com:465，163 邮箱 smtp.163.com:465，密码填邮箱的 SMTP 授权码。
EMAIL_NOTIFICATIONS_ENABLED = bool(os.environ.get("EMAIL_HOST"))

if EMAIL_NOTIFICATIONS_ENABLED:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.environ["EMAIL_HOST"]
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "465"))
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
    EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "1") == "1"
    EMAIL_USE_TLS = not EMAIL_USE_SSL and (
        os.environ.get("EMAIL_USE_TLS", "0") == "1"
    )
    EMAIL_TIMEOUT = 10
    DEFAULT_FROM_EMAIL = os.environ.get(
        "DEFAULT_FROM_EMAIL",
        EMAIL_HOST_USER,
    )
